"""
backend/app.py
--------------
Step 4: run the REST API that the frontend calls.

USAGE
-----
  python backend/app.py        (works from any working directory)

ENDPOINTS
---------
  GET  /                              health check
  GET  /landmarks                     all landmark metadata
  GET  /landmarks/<id>                single landmark metadata
  POST /predict                       { image: <base64 jpeg/png> }
                                       returns { landmark_id, name, confidence, top5, info }
  GET  /plan?start=<id>&minutes=<n>   dynamic walking route via OSRM
  GET  /route                         static fallback (pre-generated by plan_route.py)
"""

import json
import base64
import io
import os
import time
from pathlib import Path

import numpy as np
from flask import Flask, jsonify, request, send_from_directory, current_app
from flask_cors import CORS
import keras
from PIL import Image

# route_planner.py lives in this same directory (backend/), so this is a
# plain relative import — NOT "from backend.route_planner import ...".
# That package-style form only works if this file is launched as
# `python -m backend.app` from the project root; running it directly with
# `python backend/app.py` (the documented, normal way to start this server)
# makes Python treat backend/ as a script directory, not a package, and the
# package-style import raises ModuleNotFoundError: No module named 'backend'.
from route_planner import plan_route, plan_custom_route
from logging_setup import setup_logging


class RateLimiter:
    """Simple in-memory sliding-window rate limiter."""

    def __init__(self, max_requests=30, window_seconds=60):
        self.max_requests = max_requests
        self.window_seconds = window_seconds
        self._requests = {}  # ip -> [timestamps]

    def is_allowed(self, key):
        import time
        now = time.time()
        cutoff = now - self.window_seconds
        self._requests.setdefault(key, [])
        self._requests[key] = [t for t in self._requests[key] if t > cutoff]
        if len(self._requests[key]) >= self.max_requests:
            return False
        self._requests[key].append(now)
        return True


_workers = int(os.environ.get("GUNICORN_WORKERS", "2"))
_osrm_limiter = RateLimiter(max_requests=10 // _workers, window_seconds=60)

logger = setup_logging("app")


# ── metrics ───────────────────────────────────────────────────────────────────
class MetricsCollector:
    """In-memory metrics for Prometheus /metrics endpoint.

    Thread-safe per-worker (gunicorn prefork = one process per worker).
    Counters are reset on worker restart — acceptable for ephemeral
    container metrics shipped to Prometheus/Grafana.
    """

    _BUCKETS = (0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)

    def __init__(self):
        self._requests: dict[tuple[str, str, str], int] = {}
        self._confidences: list[float] = []
        self._osrm_ok = 0
        self._osrm_fail = 0
        self._start_time = time.time()

    def record_request(self, method: str, endpoint: str, status: int):
        key = (method, endpoint, str(status))
        self._requests[key] = self._requests.get(key, 0) + 1

    def record_confidence(self, confidence: float):
        self._confidences.append(confidence)

    def record_osrm(self, success: bool):
        if success:
            self._osrm_ok += 1
        else:
            self._osrm_fail += 1

    def render(self) -> str:
        lines = []
        lines.append("# HELP pushkinskaya_http_requests_total Total HTTP requests handled")
        lines.append("# TYPE pushkinskaya_http_requests_total counter")
        for (method, endpoint, status), count in sorted(self._requests.items()):
            lines.append(
                f'pushkinskaya_http_requests_total{{method="{method}",'
                f'endpoint="{endpoint}",status="{status}"}} {count}'
            )

        lines.append("# HELP pushkinskaya_prediction_confidence Prediction confidence distribution")
        lines.append("# TYPE pushkinskaya_prediction_confidence histogram")
        buckets = [0] * len(self._BUCKETS)
        for c in self._confidences:
            for i, boundary in enumerate(self._BUCKETS):
                if c <= boundary:
                    buckets[i] += 1
                    break
        for i, boundary in enumerate(self._BUCKETS):
            lines.append(f"pushkinskaya_prediction_confidence_bucket{{le=\"{boundary}\"}} {buckets[i]}")
        lines.append(f"pushkinskaya_prediction_confidence_bucket{{le=\"+Inf\"}} {len(self._confidences)}")
        lines.append(f"pushkinskaya_prediction_confidence_count {len(self._confidences)}")
        if self._confidences:
            lines.append(f"pushkinskaya_prediction_confidence_sum {sum(self._confidences):.6f}")

        lines.append("# HELP pushkinskaya_osrm_requests_total OSRM routing requests")
        lines.append("# TYPE pushkinskaya_osrm_requests_total counter")
        lines.append(f"pushkinskaya_osrm_requests_total{{status=\"ok\"}} {self._osrm_ok}")
        lines.append(f"pushkinskaya_osrm_requests_total{{status=\"fail\"}} {self._osrm_fail}")

        lines.append("# HELP pushkinskaya_uptime_seconds Server uptime in seconds")
        lines.append("# TYPE pushkinskaya_uptime_seconds gauge")
        lines.append(f"pushkinskaya_uptime_seconds {time.time() - self._start_time:.1f}")

        return "\n".join(lines) + "\n"


_metrics = MetricsCollector()

# ── paths — anchored to project root, independent of CWD ─────────────────────
PROJECT_ROOT     = Path(__file__).resolve().parent.parent
MODELS_DIR       = PROJECT_ROOT / "models"
DATA_DIR         = PROJECT_ROOT / "data"
FRONTEND_DIR     = PROJECT_ROOT / "frontend"
MODEL_PATH       = Path(os.environ.get("MODEL_PATH", str(PROJECT_ROOT / "models" / "landmark_classifier.keras")))
CLASS_NAMES_PATH = MODELS_DIR / "class_names.json"
LANDMARKS_PATH   = DATA_DIR / "landmarks.json"
PHOTOS_DIR       = DATA_DIR / "photos"

IMG_SIZE             = (224, 224)
PORT                 = 5000
HOST                 = "0.0.0.0"
CONFIDENCE_THRESHOLD = 0.40   # predictions below this are reported as "unknown"
MAX_CONTENT_MB       = 10     # max request body size in MB
# ────────────────────────────────────────────────────────────────────────────

app = Flask(__name__, static_folder=str(FRONTEND_DIR))
app.config["MAX_CONTENT_LENGTH"] = MAX_CONTENT_MB * 1024 * 1024
_cors_origins = os.environ.get("CORS_ORIGINS", "http://localhost:*|http://127.0.0.1:*")
CORS(app, origins=[o.strip() for o in _cors_origins.split("|")])


@app.before_request
def _start_timer():
    request._start_time = time.time()


@app.after_request
def _record_metrics(response):
    endpoint = request.endpoint or request.path
    _metrics.record_request(request.method, endpoint, response.status_code)
    return response


@app.errorhandler(413)
def request_entity_too_large(e):
    return jsonify({"error": f"Request body too large. Maximum size is {MAX_CONTENT_MB}MB."}), 413


# Runtime state stored as app attributes to avoid module-level scoping issues.
app.model           = None
app.class_names     = []
app.landmarks_by_id = {}


def _is_lfs_pointer(path: Path) -> bool:
    """Return True if the file is a Git LFS pointer stub, not the real content."""
    if path.stat().st_size > 1024:
        return False
    try:
        return path.read_text(encoding="utf-8", errors="ignore") \
                   .startswith("version https://git-lfs.github.com")
    except Exception:
        return False


def load_resources():
    """Load model, class names, and landmark metadata into app state."""
    if MODEL_PATH.exists() and not _is_lfs_pointer(MODEL_PATH):
        app.model = keras.models.load_model(MODEL_PATH)
        logger.info("Model loaded from %s", MODEL_PATH)
    elif MODEL_PATH.exists():
        logger.error(
            "Model at %s is a Git LFS pointer — run 'git lfs pull' to "
            "fetch the real file. /predict will return 503 until then.",
            MODEL_PATH,
        )
    else:
        logger.error(
            "Model not found at %s — run train.py first. "
            "/predict will return 503.",
            MODEL_PATH,
        )

    if CLASS_NAMES_PATH.exists():
        app.class_names = json.loads(CLASS_NAMES_PATH.read_text())
    else:
        logger.warning("%s not found. Run train.py first.", CLASS_NAMES_PATH)

    if LANDMARKS_PATH.exists():
        data = json.loads(LANDMARKS_PATH.read_text())
        app.landmarks_by_id = {lm["id"]: lm for lm in data["landmarks"]}
    else:
        raise FileNotFoundError(f"landmarks.json not found at {LANDMARKS_PATH}")

    logger.info("Classes loaded: %d", len(app.class_names))
    logger.info("Landmarks in DB: %d", len(app.landmarks_by_id))


def preprocess_image(image_bytes: bytes) -> np.ndarray:
    """Decode, resize, normalise to [0,1], add batch dim."""
    img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    img = img.resize(IMG_SIZE, Image.LANCZOS)
    arr = np.array(img, dtype=np.float32) / 255.0
    return np.expand_dims(arr, axis=0)


def decode_base64_image(b64_string: str) -> bytes:
    """Handle both raw base64 and data-URI prefixed strings."""
    if "," in b64_string:
        b64_string = b64_string.split(",", 1)[1]
    return base64.b64decode(b64_string)


def haversine_m(lat1, lon1, lat2, lon2):
    import math
    R = 6_371_000
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2) ** 2
    return 2 * R * math.asin(math.sqrt(a))


# ── routes ───────────────────────────────────────────────────────────────────
@app.route("/")
def health():
    model_ok = current_app.model is not None
    landmarks_ok = len(current_app.landmarks_by_id) > 0

    body = {
        "status": "ok" if (model_ok and landmarks_ok) else "degraded",
        "model_loaded": model_ok,
        "classes": len(current_app.class_names),
        "landmarks": len(current_app.landmarks_by_id),
    }

    # A health check that always returns 200 is invisible to load
    # balancers and orchestrators — they only look at the status code,
    # not the body. If the model failed to load, this needs to fail
    # loudly (503) so a deployment gets flagged or rolled back instead
    # of silently serving broken /predict requests.
    status_code = 200 if (model_ok and landmarks_ok) else 503
    return jsonify(body), status_code


@app.route("/metrics")
def metrics():
    """Prometheus-compatible metrics endpoint."""
    from flask import Response
    return Response(_metrics.render(), mimetype="text/plain; version=0.0.4; charset=utf-8")


@app.route("/landmarks")
def get_landmarks():
    return jsonify(list(current_app.landmarks_by_id.values()))


@app.route("/landmarks/<landmark_id>")
def get_landmark(landmark_id: str):
    lm = current_app.landmarks_by_id.get(landmark_id)
    if lm is None:
        return jsonify({"error": "Not found"}), 404
    return jsonify(lm)


@app.route("/nearby")
def nearby():
    try:
        lat = float(request.args.get("lat"))
        lon = float(request.args.get("lon"))
    except (TypeError, ValueError):
        return jsonify({"error": "Provide numeric lat and lon query params"}), 400
    radius_m = float(request.args.get("radius_m", 500))

    geocoded = [
        lm for lm in current_app.landmarks_by_id.values()
        if lm.get("lat") is not None and lm.get("lon") is not None
    ]

    in_range = []
    nearest_overall = None
    nearest_dist = None

    for lm in geocoded:
        dist = haversine_m(lat, lon, lm["lat"], lm["lon"])
        if nearest_dist is None or dist < nearest_dist:
            nearest_dist = dist
            nearest_overall = lm
        if dist <= radius_m:
            in_range.append({**lm, "distance_m": round(dist, 1)})

    in_range.sort(key=lambda x: x["distance_m"])

    # Always report how far the nearest landmark actually is, even when
    # nothing falls inside the requested radius. Without this, a tourist
    # in Moscow or abroad gets an empty list and no indication of why —
    # it looks identical to a bug. With it, the frontend can say "you're
    # 1,100 km away" instead of silently showing nothing.
    response = {
        "query": {"lat": lat, "lon": lon, "radius_m": radius_m},
        "count": len(in_range),
        "landmarks": in_range,
    }
    if nearest_overall is not None:
        response["nearest_landmark_distance_m"] = round(nearest_dist, 1)
        response["nearest_landmark_name"] = nearest_overall["name"]

    return jsonify(response)


@app.route("/plan", methods=["GET"])
def dynamic_plan():
    """
    Dynamic route planning via OSRM — computed live, no pre-generated file needed.

    Query params:
      start   : landmark id (required)
      minutes : int, time budget in minutes (default 60)
      visit   : int, minutes spent per stop (optional). If omitted, each
                stop's dwell time is estimated automatically from its
                landmark type (a museum gets more time than a sculpture)
                instead of every stop costing the same fixed amount.
                Pass this only to force every stop to the same duration.
    """
    start_id = request.args.get("start")
    if not start_id:
        return jsonify({"error": "Missing 'start' landmark id"}), 400

    try:
        minutes = int(request.args.get("minutes", 60))
        visit_param = request.args.get("visit")
        visit_minutes = int(visit_param) if visit_param is not None else None
    except ValueError:
        return jsonify({"error": "minutes and visit must be integers"}), 400

    geocoded = [lm for lm in current_app.landmarks_by_id.values() if lm.get("lat") is not None]
    if len(geocoded) < 2:
        return jsonify({"error": "Not enough geocoded landmarks (need at least 2)."}), 400

    if not _osrm_limiter.is_allowed(request.remote_addr):
        return jsonify({"error": "Rate limit exceeded. Try again in a minute."}), 429

    try:
        start_idx = next(i for i, lm in enumerate(geocoded) if lm["id"] == start_id)
    except StopIteration:
        return jsonify({"error": f"Landmark '{start_id}' not found or has no coordinates."}), 404

    try:
        route_data = plan_route(geocoded, start_idx, minutes, visit_minutes)
    except Exception as e:
        _metrics.record_osrm(False)
        logger.error("OSRM routing failed for start=%s minutes=%s: %s", start_id, minutes, e)
        return jsonify({"error": f"OSRM routing failed: {str(e)}"}), 503

    _metrics.record_osrm(True)
    return jsonify(route_data)


@app.route("/plan-custom", methods=["POST"])
def plan_custom():
    """
    Plan a walking route for user-selected landmarks.

    POST body:
      {
        "landmarks": ["id1", "id2", ...],  (required, list of landmark IDs)
        "start": "id1",                     (required, starting landmark ID)
        "optimize": true                    (optional, default true)
      }
    """
    body = request.get_json(silent=True)
    if not body or "landmarks" not in body or "start" not in body:
        return jsonify({"error": "Send JSON with 'landmarks' (list of IDs) and 'start' (landmark ID)"}), 400

    landmark_ids = body["landmarks"]
    start_id = body["start"]
    optimize = body.get("optimize", True)

    if not isinstance(landmark_ids, list) or len(landmark_ids) == 0:
        return jsonify({"error": "'landmarks' must be a non-empty list of landmark IDs"}), 400

    landmarks = [current_app.landmarks_by_id[lid] for lid in landmark_ids if lid in current_app.landmarks_by_id]
    if len(landmarks) == 0:
        return jsonify({"error": "None of the provided landmark IDs were found"}), 404

    geocoded = [lm for lm in landmarks if lm.get("lat") is not None]
    if len(geocoded) < 1:
        return jsonify({"error": "Selected landmarks need GPS coordinates"}), 400

    if not _osrm_limiter.is_allowed(request.remote_addr):
        return jsonify({"error": "Rate limit exceeded. Try again in a minute."}), 429

    try:
        route_data = plan_custom_route(geocoded, start_id, optimize_order=optimize)
    except Exception as e:
        _metrics.record_osrm(False)
        logger.error("OSRM routing failed for custom route: %s", e)
        return jsonify({"error": f"OSRM routing failed: {str(e)}"}), 503

    _metrics.record_osrm(True)
    return jsonify(route_data)


@app.route("/route")
def get_route():
    route_path = DATA_DIR / "planned_route.json"
    if not route_path.exists():
        return jsonify({"error": "No route planned yet.", "hint": "Run: python plan_route.py --minutes 60"}), 404
    return jsonify(json.loads(route_path.read_text()))


@app.route("/model/info")
def model_info():
    """Return metadata about the currently loaded model (training run, accuracy, etc.)."""
    meta_path = MODELS_DIR / "model_metadata.json"
    if not meta_path.exists():
        return jsonify({"error": "No model metadata available. Train a model first."}), 404
    return jsonify(json.loads(meta_path.read_text()))


@app.route("/predict", methods=["POST"])
def predict():
    if current_app.model is None:
        logger.error("Predict called but model is not loaded")
        return jsonify({"error": "Model not loaded. Run train.py first."}), 503

    body = request.get_json(silent=True)
    if not body or "image" not in body:
        return jsonify({"error": "Send JSON with key 'image' (base64 string)"}), 400

    try:
        img_bytes = decode_base64_image(body["image"])
        tensor    = preprocess_image(img_bytes)
    except Exception as e:
        logger.warning("Image decode failed: %s", e)
        return jsonify({"error": f"Image decode failed: {e}"}), 400

    probs = current_app.model.predict(tensor, verbose=0)[0]

    top5_idx = np.argsort(probs)[::-1][:5]
    top5 = [
        {"landmark_id": current_app.class_names[i], "confidence": float(probs[i])}
        for i in top5_idx
    ]

    best_id   = current_app.class_names[top5_idx[0]]
    best_conf = float(probs[top5_idx[0]])
    _metrics.record_confidence(best_conf)

    if best_conf < CONFIDENCE_THRESHOLD:
        return jsonify({
            "identified": False,
            "message": "Confidence too low. Try a clearer photo or a different angle.",
            "confidence": best_conf,
            "top5": top5,
        })

    info = current_app.landmarks_by_id.get(best_id, {})
    return jsonify({
        "identified": True,
        "landmark_id": best_id,
        "name": info.get("name", best_id),
        "confidence": best_conf,
        "confidence_pct": f"{best_conf * 100:.1f}%",
        "top5": top5,
        "info": info,
    })


# ── serve photos ──────────────────────────────────────────────────────────────
_PHOTO_CACHE = None

def _list_available_photos():
    global _PHOTO_CACHE
    if _PHOTO_CACHE is None:
        _PHOTO_CACHE = {p.stem for p in PHOTOS_DIR.glob("*") if p.suffix.lower() in (".jpg", ".jpeg", ".png", ".webp")}
    return _PHOTO_CACHE

@app.route("/photo/<landmark_id>")
def serve_photo(landmark_id: str):
    for ext in (".jpg", ".jpeg", ".png", ".webp"):
        p = PHOTOS_DIR / f"{landmark_id}{ext}"
        if p.exists():
            return send_from_directory(PHOTOS_DIR, p.name)
    return jsonify({"error": "No photo for this landmark"}), 404

@app.route("/photos/available")
def photos_available():
    return jsonify(list(_list_available_photos()))


# ── serve frontend ────────────────────────────────────────────────────────────
@app.route("/app")
@app.route("/app/")
def serve_frontend():
    return send_from_directory(FRONTEND_DIR, "index.html")


@app.route("/app/<path:filename>")
def serve_static(filename):
    return send_from_directory(FRONTEND_DIR, filename)


# ── main ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    load_resources()
    print(f"\nServer running at http://localhost:{PORT}")
    print(f"Frontend: http://localhost:{PORT}/app")
    app.run(host=HOST, port=PORT, debug=False, use_reloader=False)